### PR TITLE
Replace <IconButton> with <PaneHeaderIconButton>

### PR DESCRIPTION
**Pull request by rasmuswoelk**
We updated stripes-components with an IconButton component that's made specifically for PaneHeaders.

In this PR I replaced the existing IconButton's inside PaneHeaders with the new PaneHeaderIconButton component.

### CODE REVIEW

**Comment by VictorSoroka1** [comment]
Hi @rasmuswoelk, could you please update branch since one of the existing PR was just merged.

**Comment by rasmuswoelk** [comment]
@VictorSoroka1 Yup 👍 

I also just realized that we can't merge this one in yet because PaneHeaderIconButton is not yet released in a formal release of `stripes-components`.

**Comment by VictorSoroka1** [comment]
@rasmuswoelk, got it. Please add a comment here when we can do that. Thank you.

**Comment by rasmuswoelk** [comment]
Hi @VictorSoroka1 

This PR can't be merged before this project is on stripes ^2.1.0.

**Comment by VictorSoroka1** [comment]
@rasmuswoelk, got it. I will take of updates and then merge your one. Thank you.

**Comment by rasmuswoelk** [comment]
@VictorSoroka1 Thanks!

**Pull request merged**
