### PR TITLE
UIDATIMP-1285: After duplicating profiles the previous view details information is displayed

### PR DESCRIPTION
**Pull request by OleksandrHladchenko1**
## Purpose

* After duplicating profiles duplicated view details information is displayed

## Approach

* Renamed the resource name in `manifest` for all the view forms

## Refs

[UIDATIMP-1285](https://issues.folio.org/browse/UIDATIMP-1285)

## Screenshots

https://user-images.githubusercontent.com/85172747/201671432-3c8f0826-0955-4cb3-ba4f-c485c167426f.mp4

### CODE REVIEW

**Comment by OleksandrHladchenko1** [comment]
Hi @zburke! Thanks for the approach, proposed in #1249. I renamed the resource name for the view form and everything works well!

**Review by mariia-aloshyna — APPROVED** [review]

**Review by zburke — CHANGES_REQUESTED** [review]
resource names will need to change in the tests, too.

**Comment by OleksandrHladchenko1** [comment]
> resource names will need to change in the tests, too.

@zburke Done!

**Review by zburke — APPROVED** [review]
And now all the tests are green! Sweet!

**Pull request merged**
